package com.startcaft.jpa.entity;
// Generated 2015-12-25 20:37:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.startcaft.common.SexEum;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user")
public class User implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String username;
	private Date birthday;
	private SexEum sex;
	private String address;

	public User() {
	}

	@Id
	@GeneratedValue
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name="username",length=32,nullable=false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	
	@Column(name="birthday",nullable=false)
	@Temporal(TemporalType.TIMESTAMP)
	public Date getBirthday() {
		return this.birthday;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}
	
	@Column(name="sex",nullable=false,length=1)
	@Enumerated(EnumType.ORDINAL)
	public SexEum getSex() {
		return this.sex;
	}

	public void setSex(SexEum sex) {
		this.sex = sex;
	}
	
	@Column(name="address",nullable=false,length=100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", username=" + username + ", birthday=" + birthday + ", sex=" + sex + ", address="
				+ address + "]";
	}
}
